/** In `px` */
const CELL_SIZE = 5;
const FIELD_SIZE = 128;
const GRID_COLOR = "#CCCCCC";
const DEAD_COLOR = "#FFFFFF";
const ALIVE_COLOR_BASE_1 = "#FF0000";
const ALIVE_COLOR_BASE_2 = "#FFFF00";
const ALIVE_COLOR_BASE_3 = "#0000FF";
const ALIVE_COLORS = [ALIVE_COLOR_BASE_1, ALIVE_COLOR_BASE_2, ALIVE_COLOR_BASE_3];
const LIFE_SPAN = 200;

export {
  CELL_SIZE,
  FIELD_SIZE,
  GRID_COLOR,
  DEAD_COLOR,
  ALIVE_COLORS,
  LIFE_SPAN,
}
