const ALIVE_CELL_BASE_OPTIONS_DEFAULT = 10
const ALIVE_CELL_BASE_OPTIONS_ENV = process.env.ALIVE_CELL_BASE_OPTIONS && parseInt(process.env.ALIVE_CELL_BASE_OPTIONS)
export const ALIVE_CELL_BASE_OPTIONS = ALIVE_CELL_BASE_OPTIONS_ENV || ALIVE_CELL_BASE_OPTIONS_DEFAULT
