name: Test WWW
on:
  pull_request:
  workflow_dispatch:

jobs:
  build-wasm:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Install wasm-pack
      uses: jetli/wasm-pack-action@v0.4.0
      with:
        version: 'latest'
    - name: Build wasm
      run: wasm-pack build
  build:
    runs-on: ubuntu-22.04
    needs: build-wasm
    strategy:
      matrix:
        node-version: [20]
    steps:
    - uses: actions/checkout@v4
    - name: Install pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 9
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
        cache-dependency-path: '**/pnpm-lock.yaml'
    - name: Change directory to www
      run: cd www
    - name: Install dependencies
      run: pnpm install
    - name: Run Tests
      run: pnpm test